export const SEARCH_JOB = "searchJob"
export const FILTER_JOB_TYPE = "filterJobType"
export const FILTER_JOB_STATUS = "filterJobStatus"
export const FIND_APPLICANTS = "findApplicants"
export const GET_RECRUITER = "getRecruiter"
export const FREELANCER_LOCAL_SERACH = "localsearch"
export const CLIENT_SEARCH="clientSearch"
