export const skillsTag = [
  { value: "ruby on rails", label: "ruby on rails" },
  { value: ".net", label: ".net" },
  { value: ".net 4.6", label: ".net 4.6" },
  { value: ".net core", label: ".net core" },
  { value: "a/b testing", label: "a/b testing" },
  { value: "abap", label: "abap" },
  { value: "action cable", label: "action cable" },
  { value: "active record", label: "active record" },
  { value: "adobe creative cloud", label: "adobe creative cloud" },
  { value: "adobe suite", label: "adobe suite" },
  { value: "adobe xd", label: "adobe xd" },
  { value: "aerospike", label: "aerospike" },
  { value: "agile", label: "agile" },
  { value: "ai", label: "ai" },
  { value: "aidass", label: "aidass" },
  { value: "airflow", label: "airflow" },
  { value: "ajax", label: "ajax" },
  { value: "akka", label: "akka" },
  { value: "alteryx", label: "alteryx" },
  { value: "amazon aurora", label: "amazon aurora" },
  { value: "amazon web service", label: "amazon web service" },
  { value: "amplify", label: "amplify" },
  { value: "amqp", label: "amqp" },
  { value: "android", label: "android" },
  { value: "android & ui", label: "android & ui" },
  { value: "android application", label: "android application" },
  { value: "android jetpack", label: "android jetpack" },
  { value: "android sdk/ndk", label: "android sdk/ndk" },
  { value: "android studio", label: "android studio" },
  { value: "angular", label: "angular" },
  { value: "angular js", label: "angular js" },
  { value: "angular material", label: "angular material" },
  { value: "ansible", label: "ansible" },
  { value: "ant", label: "ant" },
  { value: "anylogic", label: "anylogic" },
  { value: "apache", label: "apache" },
  { value: "apache airflow", label: "apache airflow" },
  { value: "apache camel", label: "apache camel" },
  { value: "apache spark", label: "apache spark" },
  { value: "apache superset", label: "apache superset" },
  { value: "apache tomcat", label: "apache tomcat" },
  { value: "apis", label: "apis" },
  { value: "apollo", label: "apollo" },
  { value: "apollo graphql", label: "apollo graphql" },
  { value: "appium", label: "appium" },
  { value: "apple homekit", label: "apple homekit" },
  { value: "argocd", label: "argocd" },
  { value: "asciidoc", label: "asciidoc" },
  { value: "asp", label: "asp" },
  { value: "asp.net core", label: "asp.net core" },
  { value: "asp.net mvc", label: "asp.net mvc" },
  { value: "asynchrony", label: "asynchrony" },
  { value: "athena/presto", label: "athena/presto" },
  { value: "atlassian suite", label: "atlassian suite" },
  { value: "atomic", label: "atomic" },
  { value: "aurelia", label: "aurelia" },
  { value: "auth0", label: "auth0" },
  { value: "automated ui testing", label: "automated ui testing" },
  { value: "avro models", label: "avro models" },
  { value: "await", label: "await" },
  { value: "aws", label: "aws" },
  { value: "axios", label: "axios" },
  { value: "axure", label: "axure" },
  { value: "azure", label: "azure" },
  { value: "azure cosmos db", label: "azure cosmos db" },
  { value: "b", label: "b" },
  { value: "b2b/b2c", label: "b2b/b2c" },
  { value: "babel", label: "babel" },
  { value: "backbone.js", label: "backbone.js" },
  { value: "backstop.js", label: "backstop.js" },
  { value: "balsamiq", label: "balsamiq" },
  { value: "bamboo", label: "bamboo" },
  { value: "bash", label: "bash" },
  { value: "bdd", label: "bdd" },
  { value: "bem", label: "bem" },
  { value: "big data", label: "big data" },
  { value: "big query", label: "big query" },
  { value: "bitbucket", label: "bitbucket" },
  { value: "bitrise", label: "bitrise" },
  { value: "bluemix", label: "bluemix" },
  { value: "bluetooth (ble)", label: "bluetooth (ble)" },
  { value: "bootstrap", label: "bootstrap" },
  { value: "bower", label: "bower" },
  { value: "brakeman", label: "brakeman" },
  { value: "bugzilla", label: "bugzilla" },
  {
    value: "business technology platform",
    label: "business technology platform",
  },
  { value: "c", label: "c" },
  { value: "c#", label: "c#" },
  { value: "c++", label: "c++" },
  { value: "camerax", label: "camerax" },
  { value: "camunda", label: "camunda" },
  { value: "canvas", label: "canvas" },
  { value: "capybara", label: "capybara" },
  { value: "cassandra", label: "cassandra" },
  { value: "celery", label: "celery" },
  { value: "chai", label: "chai" },
  { value: "charles", label: "charles" },
  { value: "chartjs", label: "chartjs" },
  { value: "chef", label: "chef" },
  { value: "ci/cd", label: "ci/cd" },
  { value: "circle ci", label: "circle ci" },
  { value: "classic autosar", label: "classic autosar" },
  { value: "clojure", label: "clojure" },
  { value: "closure-compiler", label: "closure-compiler" },
  { value: "cloud foundry", label: "cloud foundry" },
  { value: "cloud run", label: "cloud run" },
  { value: "cloud sql", label: "cloud sql" },
  { value: "cloudera impala", label: "cloudera impala" },
  { value: "cloudwatch", label: "cloudwatch" },
  { value: "cluster", label: "cluster" },
  { value: "cms", label: "cms" },
  { value: "codeception", label: "codeception" },
  { value: "codecov", label: "codecov" },
  { value: "command line interface", label: "command line interface" },
  { value: "composer", label: "composer" },
  { value: "confluence", label: "confluence" },
  { value: "consul", label: "consul" },
  {
    value: "content mangement system",
    label: "content mangement system",
  },
  { value: "cordova", label: "cordova" },
  { value: "core animation", label: "core animation" },
  { value: "core data", label: "core data" },
  { value: "coremedia", label: "coremedia" },
  { value: "couchdb", label: "couchdb" },
  { value: "cqrs", label: "cqrs" },
  { value: "crashlytics", label: "crashlytics" },
  { value: "cross-browser testing", label: "cross-browser testing" },
  { value: "css", label: "css" },
  { value: "csv", label: "csv" },
  { value: "cucumber", label: "cucumber" },
  { value: "cypress", label: "cypress" },
  { value: "cytoscape", label: "cytoscape" },
  { value: "d3.js", label: "d3.js" },
  { value: "dart", label: "dart" },
  { value: "dash", label: "dash" },
  { value: "dask", label: "dask" },
  { value: "data lake", label: "data lake" },
  { value: "data layer", label: "data layer" },
  { value: "data pipeline", label: "data pipeline" },
  {
    value: "data structures and algorithms",
    label: "data structures and algorithms",
  },
  { value: "databases", label: "databases" },
  { value: "datadog", label: "datadog" },
  { value: "db2", label: "db2" },
  { value: "deep learning", label: "deep learning" },
  { value: "devops", label: "devops" },
  { value: "devops mindset", label: "devops mindset" },
  { value: "django", label: "django" },
  { value: "docker", label: "docker" },
  { value: "doctrine", label: "doctrine" },
  { value: "documentdb", label: "documentdb" },
  { value: "domain-driven design", label: "domain-driven design" },
  { value: "doors", label: "doors" },
  { value: "drupal", label: "drupal" },
  { value: "e2e tests", label: "e2e tests" },
  { value: "eathersjs", label: "eathersjs" },
  { value: "eclipse", label: "eclipse" },
  { value: "ecmascript", label: "ecmascript" },
  { value: "ef core orm", label: "ef core orm" },
  { value: "elasticsearch", label: "elasticsearch" },
  { value: "electron", label: "electron" },
  { value: "elixir", label: "elixir" },
  { value: "ember.js", label: "ember.js" },
  { value: "end to end", label: "end to end" },
  { value: "enterprise architect", label: "enterprise architect" },
  { value: "entity framework", label: "entity framework" },
  { value: "enzyme", label: "enzyme" },
  { value: "epsagon", label: "epsagon" },
  { value: "erp/crm system", label: "erp/crm system" },
  { value: "es2015", label: "es2015" },
  { value: "es6", label: "es6" },
  { value: "es64", label: "es64" },
  { value: "eslint", label: "eslint" },
  { value: "esnext", label: "esnext" },
  { value: "espresso", label: "espresso" },
  { value: "eventemitter", label: "eventemitter" },
  { value: "excel", label: "excel" },
  { value: "express", label: "express" },
  { value: "extbase", label: "extbase" },
  { value: "faas", label: "faas" },
  { value: "fabio", label: "fabio" },
  { value: "fact finder", label: "fact finder" },
  { value: "falcon", label: "falcon" },
  { value: "fastapi", label: "fastapi" },
  { value: "fastlane", label: "fastlane" },
  { value: "fastly", label: "fastly" },
  { value: "faunadb/fql", label: "faunadb/fql" },
  { value: "feathers", label: "feathers" },
  { value: "figma", label: "figma" },
  { value: "fior", label: "fior" },
  { value: "firebase", label: "firebase" },
  { value: "firebug", label: "firebug" },
  { value: "fivetran", label: "fivetran" },
  { value: "flagger", label: "flagger" },
  { value: "flask", label: "flask" },
  { value: "flectra", label: "flectra" },
  { value: "flexbox", label: "flexbox" },
  { value: "flink", label: "flink" },
  { value: "fluentd", label: "fluentd" },
  { value: "flutter", label: "flutter" },
  { value: "flux", label: "flux" },
  { value: "foundation", label: "foundation" },
  { value: "framer", label: "framer" },
  { value: "freemarker", label: "freemarker" },
  { value: "functional test", label: "functional test" },
  { value: "galen", label: "galen" },
  { value: "game design", label: "game design" },
  { value: "gcp", label: "gcp" },
  { value: "geospatial", label: "geospatial" },
  { value: "gerrit", label: "gerrit" },
  { value: "gherkin", label: "gherkin" },
  { value: "ghostlab", label: "ghostlab" },
  { value: "gin", label: "gin" },
  { value: "gis", label: "gis" },
  { value: "git", label: "git" },
  { value: "gitflow", label: "gitflow" },
  { value: "github", label: "github" },
  { value: "gitlab", label: "gitlab" },
  { value: "go", label: "go" },
  { value: "golang", label: "golang" },
  { value: "google analytics", label: "google analytics" },
  { value: "google api", label: "google api" },
  { value: "google charts", label: "google charts" },
  { value: "google cloud", label: "google cloud" },
  { value: "google maps", label: "google maps" },
  { value: "gradle", label: "gradle" },
  { value: "grafana", label: "grafana" },
  { value: "graph ql", label: "graph ql" },
  { value: "graphcms", label: "graphcms" },
  { value: "graphdb", label: "graphdb" },
  { value: "graphql", label: "graphql" },
  { value: "grid", label: "grid" },
  { value: "groovy", label: "groovy" },
  { value: "grpc", label: "grpc" },
  { value: "grunt", label: "grunt" },
  { value: "guava", label: "guava" },
  { value: "gulp", label: "gulp" },
  { value: "hadoop", label: "hadoop" },
  { value: "hapi.js", label: "hapi.js" },
  { value: "haproxy", label: "haproxy" },
  { value: "haskell", label: "haskell" },
  { value: "hateoas", label: "hateoas" },
  { value: "hbase", label: "hbase" },
  { value: "helm", label: "helm" },
  { value: "heroku", label: "heroku" },
  { value: "hibernate", label: "hibernate" },
  { value: "hive", label: "hive" },
  { value: "html", label: "html" },
  { value: "http", label: "http" },
  { value: "http apis", label: "http apis" },
  { value: "hubspot", label: "hubspot" },
  { value: "hybris", label: "hybris" },
  { value: "hype3", label: "hype3" },
  { value: "ibeacon", label: "ibeacon" },
  { value: "ibm rpg", label: "ibm rpg" },
  { value: "idea", label: "idea" },
  { value: "illustrator", label: "illustrator" },
  { value: "immutable.js", label: "immutable.js" },
  { value: "impala", label: "impala" },
  { value: "indesign", label: "indesign" },
  { value: "influxdb", label: "influxdb" },
  { value: "integration tests", label: "integration tests" },
  { value: "integromat", label: "integromat" },
  { value: "intellij", label: "intellij" },
  { value: "invision", label: "invision" },
  { value: "ionic", label: "ionic" },
  { value: "ios sdk", label: "ios sdk" },
  { value: "iot", label: "iot" },
  { value: "istqb certification", label: "istqb certification" },
  { value: "it security", label: "it security" },
  { value: "jaeger", label: "jaeger" },
  { value: "jamstack sites", label: "jamstack sites" },
  { value: "janusgraph", label: "janusgraph" },
  { value: "jasmine", label: "jasmine" },
  { value: "java", label: "java" },
  { value: "jvm", label: "jvm" },
  { value: "javascript", label: "javascript" },
  { value: "javaserver pages", label: "javaserver pages" },
  { value: "jax-rs", label: "jax-rs" },
  { value: "jboss", label: "jboss" },
  { value: "jee technology", label: "jee technology" },
  { value: "jenkins", label: "jenkins" },
  { value: "jest", label: "jest" },
  { value: "jira", label: "jira" },
  { value: "jira x-ray", label: "jira x-ray" },
  { value: "jmeter", label: "jmeter" },
  { value: "jmp", label: "jmp" },
  { value: "jms", label: "jms" },
  { value: "joint service support", label: "joint service support" },
  { value: "joomia", label: "joomia" },
  { value: "jpa", label: "jpa" },
  { value: "jquery", label: "jquery" },
  { value: "js maps", label: "js maps" },
  { value: "json", label: "json" },
  { value: "julia", label: "julia" },
  { value: "junit", label: "junit" },
  { value: "kafka", label: "kafka" },
  { value: "karaf", label: "karaf" },
  { value: "karma", label: "karma" },
  { value: "katalon studio", label: "katalon studio" },
  { value: "keras", label: "keras" },
  { value: "keycloak", label: "keycloak" },
  { value: "kibana", label: "kibana" },
  { value: "knative", label: "knative" },
  { value: "knime", label: "knime" },
  { value: "koa", label: "koa" },
  { value: "kong", label: "kong" },
  { value: "kotlin", label: "kotlin" },
  { value: "kubernetes", label: "kubernetes" },
  { value: "laminas", label: "laminas" },
  { value: "laravel", label: "laravel" },
  { value: "lazy", label: "lazy" },
  { value: "lenses.io", label: "lenses.io" },
  { value: "less", label: "less" },
  { value: "lightroom", label: "lightroom" },
  { value: "linux", label: "linux" },
  { value: "locust.io", label: "locust.io" },
  { value: "logstash", label: "logstash" },
  { value: "loki", label: "loki" },
  { value: "looker", label: "looker" },
  { value: "lucene", label: "lucene" },
  { value: "lumen", label: "lumen" },
  { value: "machine learning", label: "machine learning" },
  { value: "magento", label: "magento" },
  { value: "mariadb", label: "mariadb" },
  { value: "markup", label: "markup" },
  { value: "marvin", label: "marvin" },
  { value: "mate", label: "mate" },
  { value: "material ui", label: "material ui" },
  { value: "matlab", label: "matlab" },
  { value: "maven", label: "maven" },
  { value: "memcached", label: "memcached" },
  { value: "mercurial", label: "mercurial" },
  { value: "microservices", label: "microservices" },
  {
    value: "microsoft authentication library (msal)",
    label: "microsoft authentication library (msal)",
  },
  { value: "minitab", label: "minitab" },
  { value: "miro", label: "miro" },
  { value: "ml", label: "ml" },
  { value: "mobile app ux", label: "mobile app ux" },
  { value: "mobx", label: "mobx" },
  { value: "mocka", label: "mocka" },
  { value: "mockito", label: "mockito" },
  { value: "mongodb", label: "mongodb" },
  { value: "monorepo", label: "monorepo" },
  { value: "mqtt", label: "mqtt" },
  { value: "ms sql", label: "ms sql" },
  { value: "mvc", label: "mvc" },
  { value: "mysql", label: "mysql" },
  { value: "nakadi", label: "nakadi" },
  { value: "neo4j", label: "neo4j" },
  { value: "nest.js", label: "nest.js" },
  { value: "network protocols", label: "network protocols" },
  { value: "new relic", label: "new relic" },
  { value: "next.js", label: "next.js" },
  { value: "nexus", label: "nexus" },
  { value: "nginx", label: "nginx" },
  { value: "ngrx", label: "ngrx" },
  { value: "nightwatch", label: "nightwatch" },
  { value: "nimble", label: "nimble" },
  { value: "node package manager", label: "node package manager" },
  { value: "node.js", label: "node.js" },
  { value: "nomad", label: "nomad" },
  { value: "nosql", label: "nosql" },
  { value: "npm", label: "npm" },
  { value: "npm scripts", label: "npm scripts" },
  { value: "nunit", label: "nunit" },
  { value: "nuxt", label: "nuxt" },
  { value: "nx.dev", label: "nx.dev" },
  { value: "oauth", label: "oauth" },
  { value: "objective c", label: "objective c" },
  { value: "octane", label: "octane" },
  { value: "odata", label: "odata" },
  { value: "odoo", label: "odoo" },
  { value: "okhttp", label: "okhttp" },
  { value: "openapi", label: "openapi" },
  { value: "openid", label: "openid" },
  { value: "openjpa", label: "openjpa" },
  { value: "openshift", label: "openshift" },
  { value: "openstack", label: "openstack" },
  { value: "openui5", label: "openui5" },
  { value: "oracle", label: "oracle" },
  { value: "orm", label: "orm" },
  { value: "owasp", label: "owasp" },
  { value: "oxid", label: "oxid" },
  { value: "packer", label: "packer" },
  { value: "pagerduty", label: "pagerduty" },
  { value: "parse server", label: "parse server" },
  { value: "pearl", label: "pearl" },
  { value: "perl", label: "perl" },
  { value: "phalcon", label: "phalcon" },
  { value: "photoshop", label: "photoshop" },
  { value: "php", label: "php" },
  { value: "phpunit", label: "phpunit" },
  { value: "phypertextprocessor", label: "phypertextprocessor" },
  { value: "pimcore", label: "pimcore" },
  { value: "pixel code", label: "pixel code" },
  { value: "pki infrastructures", label: "pki infrastructures" },
  { value: "play", label: "play" },
  { value: "plotly", label: "plotly" },
  { value: "polarion", label: "polarion" },
  { value: "polymer", label: "polymer" },
  { value: "postcss", label: "postcss" },
  { value: "postgresql", label: "postgresql" },
  { value: "postman", label: "postman" },
  { value: "power bi", label: "power bi" },
  { value: "powerpoint", label: "powerpoint" },
  { value: "powershell", label: "powershell" },
  { value: "preprocessors", label: "preprocessors" },
  { value: "presto", label: "presto" },
  { value: "prodigy", label: "prodigy" },
  { value: "progressive web apps", label: "progressive web apps" },
  { value: "prometheus", label: "prometheus" },
  { value: "protobuf", label: "protobuf" },
  { value: "protopie", label: "protopie" },
  { value: "protractor", label: "protractor" },
  { value: "pub/sub", label: "pub/sub" },
  { value: "pulsar", label: "pulsar" },
  { value: "puppet", label: "puppet" },
  { value: "purescript", label: "purescript" },
  { value: "pwa", label: "pwa" },
  { value: "pycharm", label: "pycharm" },
  { value: "pyramid", label: "pyramid" },
  { value: "pyspark", label: "pyspark" },
  { value: "pytest", label: "pytest" },
  { value: "python", label: "python" },
  { value: "pytorch", label: "pytorch" },
  { value: "qf-test", label: "qf-test" },
  { value: "qlik", label: "qlik" },
  { value: "quarkus", label: "quarkus" },
  { value: "quasar", label: "quasar" },
  { value: "quick", label: "quick" },
  { value: "qunit", label: "qunit" },
  { value: "r", label: "r" },
  { value: "r shiny", label: "r shiny" },
  { value: "rabbitmq", label: "rabbitmq" },
  { value: "rack", label: "rack" },
  { value: "rackspace cloud", label: "rackspace cloud" },
  { value: "raml", label: "raml" },
  { value: "ranorex", label: "ranorex" },
  { value: "react", label: "react" },
  { value: "react native", label: "react native" },
  { value: "reactivex", label: "reactivex" },
  { value: "realm", label: "realm" },
  { value: "red shift", label: "red shift" },
  { value: "redis", label: "redis" },
  { value: "redmine", label: "redmine" },
  { value: "redshift", label: "redshift" },
  { value: "redux", label: "redux" },
  { value: "regression tests", label: "regression tests" },
  { value: "responsive web design", label: "responsive web design" },
  { value: "rest", label: "rest" },
  { value: "rest apis", label: "rest apis" },
  { value: "restful apis", label: "restful apis" },
  { value: "retrofit", label: "retrofit" },
  { value: "review board", label: "review board" },
  { value: "robot framework", label: "robot framework" },
  { value: "robotics", label: "robotics" },
  { value: "robotium", label: "robotium" },
  { value: "rollbar", label: "rollbar" },
  { value: "room", label: "room" },
  { value: "ror", label: "ror" },
  { value: "rspec", label: "rspec" },
  { value: "rubocop", label: "rubocop" },
  { value: "rust", label: "rust" },
  { value: "rx.js", label: "rx.js" },
  { value: "rxjava", label: "rxjava" },
  { value: "saas", label: "saas" },
  { value: "salesforce", label: "salesforce" },
  { value: "saltstack", label: "saltstack" },
  { value: "saml", label: "saml" },
  { value: "sanic", label: "sanic" },
  { value: "sap", label: "sap" },
  { value: "sap commerce cloud.", label: "sap commerce cloud." },
  { value: "sapui5", label: "sapui5" },
  { value: "sas", label: "sas" },
  { value: "sass", label: "sass" },
  { value: "scala", label: "scala" },
  { value: "schema", label: "schema" },
  { value: "scikit-learn", label: "scikit-learn" },
  { value: "selenium", label: "selenium" },
  { value: "semantic-ui", label: "semantic-ui" },
  { value: "sentry", label: "sentry" },
  { value: "seo", label: "seo" },
  { value: "sequelize", label: "sequelize" },
  { value: "serenity", label: "serenity" },
  { value: "serverless", label: "serverless" },
  { value: "shell script", label: "shell script" },
  { value: "shopify", label: "shopify" },
  { value: "shopware", label: "shopware" },
  { value: "sidekiq", label: "sidekiq" },
  { value: "silkuli", label: "silkuli" },
  { value: "sinon", label: "sinon" },
  { value: "sketch", label: "sketch" },
  { value: "sinatra", label: "sinatra" },
  { value: "slack", label: "slack" },
  { value: "slf4j", label: "slf4j" },
  { value: "soap", label: "soap" },
  { value: "software testing", label: "software testing" },
  { value: "solid", label: "solid" },
  { value: "solr", label: "solr" },
  { value: "some", label: "some" },
  { value: "spa frameworks", label: "spa frameworks" },
  { value: "spacy", label: "spacy" },
  { value: "spark", label: "spark" },
  { value: "sphinx", label: "sphinx" },
  { value: "spotfire", label: "spotfire" },
  { value: "spring", label: "spring" },
  { value: "spring boot", label: "spring boot" },
  { value: "spss", label: "spss" },
  { value: "sql", label: "sql" },
  { value: "sql servers", label: "sql servers" },
  { value: "sqlite", label: "sqlite" },
  { value: "sqs", label: "sqs" },
  { value: "ssh", label: "ssh" },
  { value: "stash", label: "stash" },
  { value: "stata", label: "stata" },
  { value: "statistical analysis", label: "statistical analysis" },
  { value: "stencil", label: "stencil" },
  { value: "stitch data", label: "stitch data" },
  { value: "storm", label: "storm" },
  { value: "storybook", label: "storybook" },
  { value: "streams", label: "streams" },
  { value: "stripe ap1", label: "stripe ap1" },
  { value: "stylus", label: "stylus" },
  { value: "subversion", label: "subversion" },
  { value: "supense", label: "supense" },
  { value: "svelte", label: "svelte" },
  { value: "svn", label: "svn" },
  { value: "swagger", label: "swagger" },
  { value: "swarm", label: "swarm" },
  { value: "swift", label: "swift" },
  { value: "symfony", label: "symfony" },
  { value: "tableau", label: "tableau" },
  { value: "tdd", label: "tdd" },
  { value: "tailwindcss", label: "tailwindcss" },
  { value: "tensorflow", label: "tensorflow" },
  { value: "teamcity", label: "teamcity" },
  { value: "test automation", label: "test automation" },
  { value: "testcomplete", label: "testcomplete" },
  {
    value: "test driven development",
    label: "test driven development",
  },
  { value: "testkit", label: "testkit" },
  { value: "testng", label: "testng" },
  { value: "testrail", label: "testrail" },
  { value: "three.js", label: "three.js" },
  { value: "tomcat", label: "tomcat" },
  { value: "tornado", label: "tornado" },
  { value: "twig", label: "twig" },
  { value: "typescript", label: "typescript" },
  { value: "typo3", label: "typo3" },
  { value: "typography", label: "typography" },
  { value: "typoscript", label: "typoscript" },
  { value: "ui automator", label: "ui automator" },
  { value: "ui testing", label: "ui testing" },
  { value: "ui / ux", label: "ui / ux" },
  { value: "uml", label: "uml" },
  {
    value: "unit & integration tests",
    label: "unit & integration tests",
  },
  { value: "uikit", label: "uikit" },
  { value: "unit testing", label: "unit testing" },
  { value: "unit tests", label: "unit tests" },
  { value: "user story writing", label: "user story writing" },
  { value: "unity game engine", label: "unity game engine" },
  { value: "vaadin", label: "vaadin" },
  { value: "vanillajs", label: "vanillajs" },
  { value: "varnish", label: "varnish" },
  { value: "varnish cache", label: "varnish cache" },
  { value: "vb script", label: "vb script" },
  { value: "vba", label: "vba" },
  { value: "vip", label: "vip" },
  { value: "visual studio", label: "visual studio" },
  { value: "vr/ar", label: "vr/ar" },
  { value: "vs code ide", label: "vs code ide" },
  { value: "vue.js", label: "vue.js" },
  { value: "vuepress", label: "vuepress" },
  { value: "vuetify", label: "vuetify" },
  { value: "vuex", label: "vuex" },
  { value: "web apis", label: "web apis" },
  { value: "web components", label: "web components" },
  {
    value: "web performance optimization",
    label: "web performance optimization",
  },
  { value: "web service security", label: "web service security" },
  { value: "webgl", label: "webgl" },
  { value: "weblogic", label: "weblogic" },
  { value: "webpack", label: "webpack" },
  { value: "webrtc", label: "webrtc" },
  { value: "webstorm", label: "webstorm" },
  { value: "whimsical", label: "whimsical" },
  { value: "websocket", label: "websocket" },
  { value: "wildfly technology", label: "wildfly technology" },
  { value: "wireframe", label: "wireframe" },
  { value: "woocommerce", label: "woocommerce" },
  { value: "wordpress", label: "wordpress" },
  { value: "xamarin", label: "xamarin" },
  { value: "xcode", label: "xcode" },
  { value: "xctest", label: "xctest" },
  { value: "xd", label: "xd" },
  { value: "xml", label: "xml" },
  { value: "xplenty", label: "xplenty" },
  { value: "yarn", label: "yarn" },
  { value: "yeoman", label: "yeoman" },
  { value: "yml", label: "yml" },
  { value: "zapier", label: "zapier" },
  { value: "zend", label: "zend" },
  { value: "youtrack", label: "youtrack" },
  {
    value: "zeplin",
    label: "zeplin",
  },
  {
    value: "zookeeper",
    label: "zookeeper",
  },
];

export default skillsTag;
