export const ADMIN_GET_FREELANCERS  = "getFreelancers"
export const ADMIN_GET_RECRUITERS = "getRecruiters"
export const ADMIN_DELETE_USER = "deleteUsers"
export const ADMIN_DEACTIVE_USER = "deactivateUser"
export const ADMIN_LOCK_USER = "lockUser"
export const GET_FREELANCER_TOTALS = "freelancerTotals"
export const GET_CATEGORIES="getCategories"
export const ADD_CATEGORIES="addCategories"